language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.2'
env:
  - OSTICKET_VERSION="v1.9.15"
  - OSTICKET_VERSION="v1.10.5"
  - OSTICKET_VERSION="v1.11"
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - wget https://github.com/osTicket/osTicket/releases/download/${OSTICKET_VERSION}/osTicket-${OSTICKET_VERSION}.zip
  - unzip osTicket-${OSTICKET_VERSION}.zip
  - mv osTicket-${OSTICKET_VERSION}.zip osTicket
  - ls osTicket
  - ls osTicket/upload
  - ls osTicket/upload/include
  - ls osTicket/upload/include/plugins
  - cp -Rf plugin osTicket/upload/include/plugins/
