language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - git clone https://github.com/osTicket/osTicket.git
